bin/bt: fix bug after activating pipefail

diff --git a/bin/bt b/bin/bt
--- a/bin/bt
+++ b/bin/bt
@@ -2,6 +2,7 @@
 # vim: set syntax bash
 
 set -euo pipefail
+#set -x
 
 declare -A devices=(
     ["edifier"]="40:EF:4C:C3:AB:3F"
@@ -35,22 +36,24 @@ function connect {
         echo -e "power on\nconnect $mac\nquit" | bluetoothctl
 
         # wait until device is connected
-        echo "Waiting until device is connected ..."
+        echo -n "Waiting until device is connected ..."
         local tryCount=0
-        while [ $(isConnected $1) -ne 0 -a $tryCount -lt 5 ];
+        while [[ $(isConnected $1) -ne 0 && ${tryCount} -lt 5 ]];
         do
+            ((tryCount+=1))
+            echo -n "."
             sleep 1
-            (( tryCount++ ))
         done
+        echo
 
-        if [ $(isConnected $1) -eq 0 ];
+        if [[ $(isConnected $1) -eq 0 ]];
         then
             echo "Device is connected. Waiting until it's active ..."
             local tryCount=0
-            while [ $(isActive $1) -ne 0 -a $tryCount -lt 5 ];
+            while [[ $(isActive $1) -ne 0 && ${tryCount} -lt 5 ]];
             do
                 sleep 1
-                (( tryCount++ ))
+                ((tryCount+=1))
             done
 
             if [ $(isActive $1) -eq 0 ];
@@ -61,6 +64,8 @@ function connect {
                 echo "Device can't be activated. Trying to reconnect."
                 disconnect $1
             fi
+        else
+            echo "Can't connect. Trying to reconnect."
         fi
     done
 
@@ -80,7 +85,7 @@ function disconnect {
         while [ $(isConnected $1) -eq 0 -a $tryCount -lt 5 ];
         do
             sleep 1
-            (( tryCount++ ))
+            ((tryCount+=1))
         done
 
         if [ $(isConnected $1) -ne 0 ];
@@ -102,7 +107,7 @@ function unmount {
 
 function isConnected {
     local mac="${devices[$1]}"
-    echo -e "info $mac" | bluetoothctl | grep "Connected: yes" > /dev/null
+    (set +o pipefail; echo -e "info $mac" | bluetoothctl | grep "Connected: yes" > /dev/null)
     echo $?
 }
 
